// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;

namespace CMoney.DataAccess.Lib.Models
{
    public partial class CmoneyContext : DbContext
    {
        public CmoneyContext()
        {
        }

        public CmoneyContext(DbContextOptions<CmoneyContext> options)
            : base(options)
        {
        }

        public virtual DbSet<SingleStock> SingleStock { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<SingleStock>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.ByDate).HasComment("資料日期");

                entity.Property(e => e.DividendYear).HasComment("股利年度");

                entity.Property(e => e.FinancialYear)
                    .IsUnicode(false)
                    .HasComment("財報年度");

                entity.Property(e => e.Peratio).HasComment("本益比");

                entity.Property(e => e.PriceRatio).HasComment("股價淨值比");

                entity.Property(e => e.SecuritiesCode)
                    .IsUnicode(false)
                    .HasComment("證券代號");

                entity.Property(e => e.SecuritiesName).HasComment("證券名稱");

                entity.Property(e => e.YieldRate).HasComment("殖利率");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}