// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CMoney.DataAccess.Lib.Models
{
    public partial class SingleStock
    {
        [Key]
        public Guid Id { get; set; }
        /// <summary>
        /// 證券代號
        /// </summary>
        [Required]
        [StringLength(10)]
        public string SecuritiesCode { get; set; }
        /// <summary>
        /// 證券名稱
        /// </summary>
        [Required]
        [StringLength(10)]
        public string SecuritiesName { get; set; }
        /// <summary>
        /// 殖利率
        /// </summary>
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? YieldRate { get; set; }
        /// <summary>
        /// 股利年度
        /// </summary>
        public short DividendYear { get; set; }
        /// <summary>
        /// 本益比
        /// </summary>
        [Column("PERatio", TypeName = "decimal(18, 2)")]
        public decimal? Peratio { get; set; }
        /// <summary>
        /// 股價淨值比
        /// </summary>
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? PriceRatio { get; set; }
        /// <summary>
        /// 財報年度
        /// </summary>
        [Required]
        [StringLength(10)]
        public string FinancialYear { get; set; }
        /// <summary>
        /// 資料日期
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime ByDate { get; set; }
    }
}